### ISSUE TITLE
#14 was prematurely merged

### ISSUE THREAD

**Issue by panva** [tireddy2/JOSE_HPKE#16]
> The JWE way of doing this is IMHO to use "alg":"dir" and "enc": "HPKE...". This would remove the restriction to only support compact mode (which i assume is to prevent "enc" being slapped in to an unprotected header) and comply with JWE RFC7516 section 4.1.2 and is inline with the previous statement of "HPKE is employed to directly encrypt the plaintext"

_Originally posted by @panva in https://github.com/tireddy2/JOSE_HPKE/pull/14#discussion_r1485583703_

**Comment by panva** [comment]
Other unresolved comments are also left in #14

**Comment by panva** [comment]
> Rather than dictating parameter header placement in the different headers in single/multi use I feel it is more appropriate and inline with JOSE to say only what must be in a protected header when required for the security properties of hpke. 

The implications stemming from protected header use to single/multi recipient support are then, well, implied. The current enumeration is otherwise incomplete

**Comment by OR13** [comment]
I gathered some (all?) of your suggest into https://github.com/tireddy2/JOSE_HPKE/pull/19
