### ISSUE TITLE
kty EK restricted to HPKE?

### ISSUE THREAD

**Issue by OR13** [tireddy2/JOSE_HPKE#18]
Should this kty say "ek" is only "enc" as produced from an HPKE Kem, or should it say "ek" is any "encapsulated key" from "any kem" ?

**Comment by tireddy2** [comment]
It looks specific to HPKE KEM because "ek" is not required with PQC KEM (e.g., Kyber).

**Comment by OR13** [comment]
I'd feel much better about after seeing examples of Kyber / RSA Kem, that are not using this draft.

**Comment by tireddy2** [comment]
PQC KEM Encaps only outputs ciphertext and shared secret (see https://www.ietf.org/archive/id/draft-ietf-pquip-pqc-engineers-02.html#section-10.1). The sender has to only send ciphertext to the recipient unlike HPKE Seal (but equivalent to HPKE Encap).

**Comment by OR13** [comment]
I wonder if the proposal to concat enc and ct is worth revisiting in light of this.
